on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      build_dep: |
        gardenlinux/package-golang 1.26.2-1gl0+bp2150
        gardenlinux/package-golang-defaults 1.26gl0+bp2150
